# Generated by Django 5.1.3 on 2024-11-06 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='shor_name',
            new_name='short_name',
        ),
    ]
